"""
SQL Service for executing queries against clinical databases.

Connects to data sources (PostgreSQL, DuckDB) and executes SQL queries
generated by the LLM or directly for intent A queries.
"""
import re
from typing import Optional, Dict, Any, List, Tuple
from uuid import UUID

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from app.core.utils.logging import get_logger
from app.core.config import get_settings
from app.core.prompts import get_sql_generator_prompt
from app.core.encryption import decrypt_value

logger = get_logger(__name__)

# Cache for database engines (connection pooling)
_ENGINE_CACHE: Dict[str, Engine] = {}


class SQLService:
    """
    Service for executing SQL queries against clinical data sources.
    
    Features:
    - Natural language to SQL conversion
    - Direct SQL execution
    - Result formatting for LLM consumption
    - Schema caching for performance
    """
    
    def __init__(
        self,
        db_url: str,
        schema: Optional[str] = None,
        max_result_rows: int = 100,
    ):
        """
        Initialize SQL service with a database URL.
        
        Args:
            db_url: Database connection URL (postgresql://, duckdb://, etc.)
            schema: Optional schema name for table discovery
            max_result_rows: Maximum rows to return (default 100)
        """
        self._db_url = db_url
        self._schema = schema
        self._max_result_rows = max_result_rows
        self._engine: Optional[Engine] = None
        self._cached_schema: Optional[str] = None
        self._table_names: List[str] = []
        self._settings = get_settings()
    
    def _get_engine(self) -> Engine:
        """Get or create a database engine with connection pooling."""
        if self._engine is not None:
            return self._engine
        
        # Check cache
        if self._db_url in _ENGINE_CACHE:
            self._engine = _ENGINE_CACHE[self._db_url]
            return self._engine
        
        # Create new engine
        try:
            # Handle DuckDB specially
            if self._db_url.startswith("duckdb://"):
                # DuckDB uses different connection parameters
                file_path = self._db_url.replace("duckdb://", "")
                self._engine = create_engine(
                    f"duckdb:///{file_path}",
                    connect_args={"read_only": True},
                )
            else:
                # PostgreSQL, MySQL, etc.
                self._engine = create_engine(
                    self._db_url,
                    pool_size=5,
                    max_overflow=10,
                    pool_timeout=30,
                    pool_recycle=3600,
                )
            
            _ENGINE_CACHE[self._db_url] = self._engine
            logger.info("Database engine created", db_url=self._db_url[:50] + "...")
            return self._engine
            
        except Exception as e:
            logger.error(f"Failed to create database engine: {e}")
            raise
    
    def _discover_tables(self) -> List[str]:
        """Discover available tables in the database."""
        if self._table_names:
            return self._table_names
        
        engine = self._get_engine()
        
        try:
            with engine.connect() as conn:
                # Try information_schema first (works for PostgreSQL, MySQL)
                try:
                    result = conn.execute(text("""
                        SELECT table_name 
                        FROM information_schema.tables 
                        WHERE table_type = 'BASE TABLE'
                        AND table_schema NOT IN ('pg_catalog', 'information_schema')
                        ORDER BY table_name
                    """))
                    self._table_names = [row[0] for row in result]
                except Exception:
                    # Fallback for DuckDB or other databases
                    try:
                        result = conn.execute(text("SHOW TABLES"))
                        self._table_names = [row[0] for row in result]
                    except Exception:
                        self._table_names = []
            
            logger.info(f"Discovered {len(self._table_names)} tables")
            return self._table_names
            
        except Exception as e:
            logger.error(f"Failed to discover tables: {e}")
            return []
    
    def get_schema_context(self, max_tables: int = 10) -> str:
        """
        Get database schema as context for LLM queries.
        
        Returns a formatted string describing tables and their columns.
        """
        if self._cached_schema:
            return self._cached_schema
        
        tables = self._discover_tables()[:max_tables]
        engine = self._get_engine()
        
        schema_parts = []
        
        try:
            with engine.connect() as conn:
                for table in tables:
                    try:
                        # Get column info
                        result = conn.execute(text(f"""
                            SELECT column_name, data_type, is_nullable
                            FROM information_schema.columns
                            WHERE table_name = :table
                            ORDER BY ordinal_position
                        """), {"table": table})
                        
                        columns = [(row[0], row[1], row[2]) for row in result]
                        
                        if columns:
                            col_desc = ", ".join([
                                f"{name} ({dtype}{'?' if nullable == 'YES' else ''})"
                                for name, dtype, nullable in columns[:20]  # Limit columns
                            ])
                            schema_parts.append(f"- {table}: {col_desc}")
                    except Exception:
                        schema_parts.append(f"- {table}: (columns unavailable)")
            
            self._cached_schema = "Tables:\n" + "\n".join(schema_parts)
            return self._cached_schema
            
        except Exception as e:
            logger.error(f"Failed to get schema context: {e}")
            return f"Tables: {', '.join(tables)}"
    
    @property
    def cached_schema(self) -> str:
        """Get cached schema or generate it."""
        return self.get_schema_context()
    
    def execute_query(self, sql: str) -> Tuple[List[Dict[str, Any]], int]:
        """
        Execute a SQL query and return results.
        
        Args:
            sql: SQL query to execute
            
        Returns:
            Tuple of (results as list of dicts, total row count)
        """
        engine = self._get_engine()
        
        # Sanitize query - add LIMIT if not present
        sql_upper = sql.upper()
        if "LIMIT" not in sql_upper and "SELECT" in sql_upper:
            sql = f"{sql.rstrip(';')} LIMIT {self._max_result_rows}"
        
        try:
            with engine.connect() as conn:
                result = conn.execute(text(sql))
                rows = result.fetchall()
                columns = result.keys()
                
                # Convert to list of dicts
                results = [dict(zip(columns, row)) for row in rows]
                
                logger.info(f"Query executed", rows=len(results), sql=sql[:100])
                return results, len(results)
                
        except Exception as e:
            logger.error(f"Query execution failed: {e}", sql=sql[:200])
            raise
    
    def query(self, natural_language_query: str) -> str:
        """
        Execute a natural language query using LLM to generate SQL.
        
        This is the main entry point for Intent A (SQL-only) queries.
        
        Args:
            natural_language_query: User's question in natural language
            
        Returns:
            Formatted response string with query results
        """
        from app.core.llm import create_llm_provider
        from langchain_core.prompts import ChatPromptTemplate
        
        schema = self.get_schema_context()
        
        # Generate SQL using LLM
        prompt = ChatPromptTemplate.from_messages([
            ("system", get_sql_generator_prompt() + "\n\nDatabase Schema:\n{schema}"),
            ("user", "{question}")
        ])
        
        try:
            provider = create_llm_provider("openai", {
                "model": "gpt-4o-mini",
                "temperature": 0,
            })
            llm = provider.get_langchain_llm()
            
            chain = prompt | llm
            response = chain.invoke({
                "schema": schema,
                "question": natural_language_query
            })
            
            # Extract SQL from response (remove markdown code blocks if present)
            sql = response.content.strip()
            sql = re.sub(r'^```sql\s*', '', sql)
            sql = re.sub(r'\s*```$', '', sql)
            
            # Execute the generated SQL
            results, count = self.execute_query(sql)
            
            # Format results for response
            if not results:
                return "No results found for your query."
            
            # Format as readable text
            if count == 1 and len(results[0]) == 1:
                # Single value result
                value = list(results[0].values())[0]
                return f"Result: {value}"
            
            # Multiple rows - format as markdown table
            if results:
                headers = list(results[0].keys())
                header_row = " | ".join(str(h) for h in headers)
                separator = " | ".join("-" * len(str(h)) for h in headers)
                
                data_rows = []
                for row in results[:20]:  # Limit display rows
                    data_rows.append(" | ".join(str(v) for v in row.values()))
                
                table = f"{header_row}\n{separator}\n" + "\n".join(data_rows)
                
                if count > 20:
                    table += f"\n\n... and {count - 20} more rows"
                
                return table
            
            return "Query executed but returned no data."
            
        except Exception as e:
            logger.error(f"Natural language query failed: {e}")
            return f"Failed to execute query: {str(e)}"
    
    def run(self, sql: str) -> str:
        """
        Execute raw SQL and return results as a string.
        
        Used for Intent C SQL filters.
        """
        try:
            results, count = self.execute_query(sql)
            return str(results)
        except Exception as e:
            return f"Error: {str(e)}"


class SQLServiceFactory:
    """Factory for creating SQLService instances from data sources."""
    
    @staticmethod
    async def from_data_source_id(
        data_source_id: UUID,
        db_session
    ) -> Optional[SQLService]:
        """
        Create a SQLService from a data source ID.
        
        Args:
            data_source_id: UUID of the data source
            db_session: Async SQLAlchemy session
            
        Returns:
            SQLService instance or None if not found
        """
        from sqlalchemy import select
        from app.modules.data_sources.models import DataSourceModel
        
        try:
            stmt = select(DataSourceModel).where(DataSourceModel.id == data_source_id)
            result = await db_session.execute(stmt)
            data_source = result.scalar_one_or_none()
            
            if not data_source:
                logger.warning(f"Data source not found: {data_source_id}")
                return None
            
            logger.debug(f"Data source found: id={data_source_id}, type={data_source.source_type}, db_url={bool(data_source.db_url)}, duckdb_path={bool(data_source.duckdb_file_path)}")
            
            if data_source.source_type == "database":
                # Decrypt the database URL if encrypted
                db_url = data_source.db_url
                if db_url and db_url.startswith("encrypted:"):
                    db_url = decrypt_value(db_url)
                
                if not db_url:
                    logger.warning(f"Data source {data_source_id} has no db_url configured")
                    return None
                    
                return SQLService(db_url=db_url)
                
            elif data_source.source_type == "file":
                # Use DuckDB for file-based data sources
                duckdb_path = data_source.duckdb_file_path
                if duckdb_path:
                    return SQLService(db_url=f"duckdb://{duckdb_path}")
                logger.warning(f"File data source {data_source_id} has no duckdb_file_path")
                return None
                    
            logger.warning(f"Data source type not supported: {data_source.source_type}")
            return None
            
        except Exception as e:
            logger.error(f"Failed to create SQL service: {e}", exc_info=True)
            return None
    
    @staticmethod
    async def from_agent_config(
        agent_id: UUID,
        db_session
    ) -> Optional[SQLService]:
        """
        Create a SQLService from an agent's active configuration.
        
        Gets the data source from the agent's active config.
        """
        from sqlalchemy import select
        from app.modules.agents.models import AgentConfigModel
        
        try:
            # Get the active config for the agent
            # Note: is_active is Integer (0/1), not Boolean
            stmt = select(AgentConfigModel).where(
                AgentConfigModel.agent_id == agent_id,
                AgentConfigModel.is_active == 1
            )
            result = await db_session.execute(stmt)
            config = result.scalar_one_or_none()
            
            if not config:
                logger.warning(f"No active config found for agent: {agent_id}")
                return None
            
            logger.debug(f"Agent config found: id={config.id}, data_source_id={config.data_source_id}")
            
            if not config.data_source_id:
                logger.warning(f"Agent config has no data_source_id: agent={agent_id}, config_id={config.id}")
                return None
            
            return await SQLServiceFactory.from_data_source_id(
                config.data_source_id,
                db_session
            )
            
        except Exception as e:
            logger.error(f"Failed to create SQL service from agent config: {e}", exc_info=True)
            return None
