"""
SQL Service for executing queries against clinical databases.

Connects to data sources (PostgreSQL, DuckDB) and executes SQL queries
generated by the LLM or directly for intent A queries.

Features:
- Few-shot learning with similar SQL examples for improved accuracy
- Natural language to SQL conversion
- Direct SQL execution
- Result formatting for LLM consumption
- Query relevance checking to filter irrelevant queries early
"""
import asyncio
import re
from typing import Optional, Dict, Any, List, Tuple
from uuid import UUID

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

from app.core.utils.logging import get_logger
from app.core.settings import get_settings
from app.core.prompts import get_sql_generator_prompt
from app.core.encryption import decrypt_value
from app.core.utils.exceptions import IrrelevantQueryException
from app.modules.sql_examples.store import get_sql_examples_store, SQLExamplesStore
from app.modules.chat.query.query_relevance_checker import (
    get_query_relevance_checker,
    QueryRelevanceChecker,
    IRRELEVANT_PII,
    IRRELEVANT_CONTEXT,
)
from app.modules.chat.query.data_dictionary import (
    get_data_dictionary,
    DataDictionary,
)

logger = get_logger(__name__)

# Relevance check statistics (for monitoring, not logged with query content)
_relevance_stats = {
    "total_checked": 0,
    "rejected_pii": 0,
    "rejected_context": 0,
    "rejected_syntax": 0,
    "passed": 0,
}

# Cache for database engines (connection pooling)
_ENGINE_CACHE: Dict[str, Engine] = {}

# DuckDB-specific SQL rules to include in prompts
DUCKDB_SQL_RULES = """CRITICAL DUCKDB SQL RULES:
1. Window functions (LAG, LEAD, ROW_NUMBER, RANK, DENSE_RANK, FIRST_VALUE, LAST_VALUE) CANNOT be used in WHERE clause - use CTE pattern instead
2. Window functions CANNOT be used in GROUP BY clause - use CTE pattern instead
3. Aggregate functions (COUNT, SUM, AVG, MIN, MAX) CANNOT be used in WHERE clause - use subquery or CTE with HAVING
4. Date difference: Use (date1 - date2) for interval or DATEDIFF('day', start_date, end_date) with 3 arguments
5. For first/last value comparisons, ALWAYS use ROW_NUMBER() in a CTE, then filter in outer query
6. Use DATE_TRUNC('month', date_col) for date truncation, not MONTH() or DATEPART()
7. Use INTERVAL '90 days' syntax for date arithmetic, not DATE_SUB() or DATEADD()
8. For consecutive streak detection, use the ROW_NUMBER difference technique in CTEs
9. String concatenation uses || operator, not CONCAT() in some contexts
10. Boolean values are TRUE/FALSE, not 1/0
11. **TYPE CASTING FOR DATE COLUMNS**: If a date column is VARCHAR type (check schema), CAST it before date comparisons:
    - Use CAST(column_name AS TIMESTAMP) or column_name::TIMESTAMP
    - Example: WHERE CAST(created_at AS TIMESTAMP) >= CURRENT_DATE - INTERVAL '1 year'
    - Also cast before DATE_TRUNC: DATE_TRUNC('month', CAST(created_at AS TIMESTAMP))
12. **CHECK COLUMN TYPES IN SCHEMA**: Before date/numeric operations, verify the column type. If VARCHAR contains dates, cast explicitly.
13. **GREATEST/LEAST FOR ROW-WISE MIN/MAX**: To find min/max ACROSS COLUMNS in a single row, use GREATEST() and LEAST(), NOT max() or min():
    - WRONG: max(col1, col2, col3) or min(col1, col2, col3) - These are AGGREGATE functions!
    - CORRECT: GREATEST(col1, col2, col3) or LEAST(col1, col2, col3)
    - Example: SELECT GREATEST(pulse_1, pulse_2, COALESCE(pulse_3, 0)) - LEAST(pulse_1, pulse_2, COALESCE(pulse_3, 0)) AS pulse_variance
14. **COALESCE FOR NULL HANDLING**: Use COALESCE(column, default_value) to handle NULLs in calculations.
15. **AGGREGATE vs ROW-WISE FUNCTIONS**: 
    - max()/min() are AGGREGATE functions - they work ACROSS ROWS (vertical)
    - GREATEST()/LEAST() are SCALAR functions - they work ACROSS COLUMNS in a single row (horizontal)
16. **TIMEZONE-AWARE TIMESTAMPS**: If a timestamp column contains timezone info (e.g., "+0300", "UTC", "Z"), you MUST use TIMESTAMPTZ, not TIMESTAMP:
    - WRONG: CAST(created_at AS TIMESTAMP) - fails with "timestamp that is not UTC" error
    - CORRECT: CAST(created_at AS TIMESTAMPTZ) or created_at::TIMESTAMPTZ
    - Example: DATE_TRUNC('month', CAST(created_at AS TIMESTAMPTZ))
    - For columns like 'created_at', 'updated_at', always prefer TIMESTAMPTZ to be safe
17. **PREFER DEDICATED DATE COLUMNS**: If a table has both a date column (like 'ymd', 'date', 'assessment_date') AND a timestamp column (like 'created_at'), prefer the dedicated date column for date-based queries as it avoids timezone issues."""

# Query type classification keywords
QUERY_TYPE_KEYWORDS = {
    "temporal_comparison": [
        "initial", "first", "latest", "recent", "last", "earliest", "most recent",
        "between", "progression", "over time", "change", "trend", "before", "after",
        "previous", "compare.*date", "compare.*time", "historical"
    ],
    "consecutive_streak": [
        "consecutive", "streak", "in a row", "in-a-row", "sequence", "sequential",
        "continuous", "uninterrupted", "back to back", "back-to-back", "running"
    ],
    "episode_detection": [
        "episode", "gap", "session", "period", "interval", "break", "pause",
        "inactive", "activity.*gap", "time.*between", "days.*apart"
    ],
    "statistical_analysis": [
        "z-score", "zscore", "standard deviation", "stddev", "std dev",
        "anomaly", "anomalies", "outlier", "outliers", "deviation",
        "percentile", "quartile", "median", "variance", "distribution"
    ],
    "rolling_calculation": [
        "rolling", "moving average", "moving avg", "trailing", "window",
        "last.*days", "past.*days", "previous.*records", "running total",
        "cumulative", "sliding"
    ],
    "comparison": [
        "compare", "versus", " vs ", " vs.", "difference", "higher than",
        "lower than", "greater than", "less than", "more than", "above",
        "below", "exceed", "relative to", "against", "benchmark"
    ],
    "deduplication": [
        "latest record", "most recent record", "one per", "single per",
        "deduplicate", "distinct", "unique.*per", "first.*per", "last.*per"
    ],
    "aggregation": [
        "count", "sum", "average", "total", "aggregate", "group by",
        "per category", "by group", "summarize", "summary"
    ]
}


class SQLService:
    """
    Service for executing SQL queries against clinical data sources.
    
    Features:
    - Few-shot learning with similar SQL examples
    - Natural language to SQL conversion
    - Direct SQL execution
    - Result formatting for LLM consumption
    - Schema caching for performance
    """
    
    def __init__(
        self,
        db_url: str,
        schema: Optional[str] = None,
        max_result_rows: int = 100,
        enable_few_shot: bool = True,
        config_id: Optional[int] = None,
        agent_id: Optional[str] = None,
    ):
        """
        Initialize SQL service with a database URL.
        
        Args:
            db_url: Database connection URL (postgresql://, duckdb://, etc.)
            schema: Optional schema name for table discovery
            max_result_rows: Maximum rows to return (default 100)
            enable_few_shot: Enable few-shot example retrieval (default True)
            config_id: Optional agent config ID for semantic schema retrieval
            agent_id: Optional agent ID for per-agent SQL examples and data dictionary
        """
        self._db_url = db_url
        self._schema = schema
        self._max_result_rows = max_result_rows
        self._engine: Optional[Engine] = None
        self._cached_schema: Optional[str] = None
        self._table_names: List[str] = []
        self._settings = get_settings()
        self._enable_few_shot = enable_few_shot
        self._config_id = config_id  # For semantic schema retrieval
        self._agent_id = agent_id  # For per-agent SQL examples and data dictionary
        
        # Initialize query relevance checker
        self._enable_relevance_check = getattr(self._settings, 'enable_query_relevance_check', True)
        self._relevance_checker: Optional[QueryRelevanceChecker] = None
        if self._enable_relevance_check:
            try:
                self._relevance_checker = get_query_relevance_checker()
                logger.info("Query relevance checker initialized")
            except Exception as e:
                logger.warning(f"Failed to initialize relevance checker: {e}")
                self._relevance_checker = None
        
        # Initialize SQL examples store for few-shot learning (per-agent)
        self._sql_examples_store: Optional[SQLExamplesStore] = None
        if enable_few_shot:
            try:
                self._sql_examples_store = get_sql_examples_store(agent_id=agent_id)
                logger.info("SQL Examples Store initialized for few-shot learning", agent_id=agent_id)
            except Exception as e:
                logger.warning(f"Failed to initialize SQL examples store: {e}")
                self._sql_examples_store = None
        
        # Initialize data dictionary for semantic enrichment (per-agent)
        self._data_dictionary: Optional[DataDictionary] = None
        try:
            self._data_dictionary = get_data_dictionary(agent_id=agent_id)
            logger.info("Data dictionary initialized for semantic enrichment", agent_id=agent_id)
        except Exception as e:
            logger.warning(f"Failed to initialize data dictionary: {e}")
            self._data_dictionary = None
    
    def _classify_query_type(self, question: str) -> str:
        """
        Classify a natural language question into a query type category.
        
        Used to retrieve more relevant few-shot examples.
        
        Args:
            question: Natural language question
            
        Returns:
            Category string (e.g., "temporal_comparison", "consecutive_streak", etc.)
        """
        question_lower = question.lower()
        
        # Check each category's keywords
        category_scores: Dict[str, int] = {}
        
        for category, keywords in QUERY_TYPE_KEYWORDS.items():
            score = 0
            for keyword in keywords:
                if re.search(keyword, question_lower):
                    score += 1
            if score > 0:
                category_scores[category] = score
        
        if category_scores:
            best_category = max(category_scores, key=category_scores.get)
            logger.debug(f"Query classified as '{best_category}' with score {category_scores[best_category]}")
            return best_category
        
        return "general"
    
    async def _get_few_shot_examples(
        self,
        question: str,
        top_k: int = 3,
        min_score: float = 0.5
    ) -> List[Dict[str, Any]]:
        """
        Retrieve similar SQL examples for few-shot prompting.
        
        First tries category-specific retrieval, then falls back to general
        retrieval if not enough examples are found.
        
        Args:
            question: Natural language question
            top_k: Maximum number of examples to return
            min_score: Minimum similarity score threshold
            
        Returns:
            List of similar examples with question, sql, and score
        """
        if not self._sql_examples_store:
            return []
        
        try:
            query_type = self._classify_query_type(question)
            logger.debug(f"Query type: {query_type}")
            
            examples = []
            if query_type != "general":
                examples = await self._sql_examples_store.get_similar_examples(
                    question=question,
                    top_k=top_k,
                    category_filter=query_type,
                    min_score=min_score
                )
                logger.debug(f"Category-specific retrieval ({query_type}): {len(examples)} examples")
            
            if len(examples) < top_k:
                remaining = top_k - len(examples)
                general_examples = await self._sql_examples_store.get_similar_examples(
                    question=question,
                    top_k=remaining,
                    category_filter=None,
                    min_score=min_score
                )
                
                existing_questions = {ex["question"] for ex in examples}
                for ex in general_examples:
                    if ex["question"] not in existing_questions:
                        examples.append(ex)
                        existing_questions.add(ex["question"])
                
                logger.debug(f"After general retrieval: {len(examples)} total examples")
            
            return examples[:top_k]
            
        except Exception as e:
            logger.error(f"Failed to retrieve few-shot examples: {e}")
            return []
    
    def _get_data_dictionary_context(self) -> str:
        """
        Get data dictionary context for prompt enrichment.
        
        Returns relevant business definitions, default filters, and metric templates
        based on the available tables.
        
        Returns:
            Formatted string with data dictionary context
        """
        if not self._data_dictionary:
            return ""
        
        try:
            tables = self._discover_tables()
            context = self._data_dictionary.to_prompt_context(tables)
            if context:
                logger.debug(f"Added data dictionary context for {len(tables)} tables")
            return context
        except Exception as e:
            logger.warning(f"Failed to get data dictionary context: {e}")
            return ""
    
    def _format_few_shot_examples(self, examples: List[Dict[str, Any]]) -> str:
        """
        Format few-shot examples as a string for prompt injection.
        
        Args:
            examples: List of example dicts with question, sql, score
            
        Returns:
            Formatted string with examples
        """
        if not examples:
            return ""
        
        formatted_parts = ["SIMILAR SQL EXAMPLES (use these patterns as reference):", ""]
        
        for i, example in enumerate(examples, 1):
            score = example.get("score", 0)
            question = example.get("question", "")
            sql = example.get("sql", "")
            category = example.get("category", "general")
            
            formatted_parts.append(f"Example {i} (similarity: {score:.2f}, category: {category}):")
            formatted_parts.append(f"Q: {question}")
            formatted_parts.append("SQL:")
            formatted_parts.append(sql)
            formatted_parts.append("")
        
        return "\n".join(formatted_parts)
    
    def _is_duckdb(self) -> bool:
        """Check if the database is DuckDB."""
        return self._db_url.startswith("duckdb://")
    
    def _get_engine(self) -> Engine:
        """Get or create a database engine with connection pooling."""
        if self._engine is not None:
            return self._engine
        
        # Normalize the database URL (handle postgres:// -> postgresql://)
        db_url = self._db_url
        if db_url.startswith("postgres://"):
            db_url = db_url.replace("postgres://", "postgresql://", 1)
            logger.debug(f"Normalized database URL from postgres:// to postgresql://")
        
        # Check cache
        if db_url in _ENGINE_CACHE:
            self._engine = _ENGINE_CACHE[db_url]
            return self._engine
        
        # Create new engine
        try:
            # Handle DuckDB specially
            if db_url.startswith("duckdb://"):
                # DuckDB uses different connection parameters
                file_path = self._db_url.replace("duckdb://", "")
                self._engine = create_engine(
                    f"duckdb:///{file_path}",
                    connect_args={"read_only": True},
                )
            else:
                # PostgreSQL, MySQL, etc.
                self._engine = create_engine(
                    db_url,
                    pool_size=5,
                    max_overflow=10,
                    pool_timeout=30,
                    pool_recycle=3600,
                )
            
            _ENGINE_CACHE[db_url] = self._engine
            logger.info("Database engine created", db_url=db_url[:50] + "...")
            return self._engine
            
        except Exception as e:
            logger.error(f"Failed to create database engine: {e}")
            raise
    
    def _discover_tables(self) -> List[str]:
        """Discover available tables in the database, excluding internal/metadata tables."""
        if self._table_names:
            return self._table_names
        
        engine = self._get_engine()
        
        try:
            with engine.connect() as conn:
                all_tables = []
                
                if self._is_duckdb():
                    # For DuckDB: include both tables AND views (uploaded files are registered as views)
                    try:
                        result = conn.execute(text("""
                            SELECT table_name 
                            FROM information_schema.tables 
                            WHERE table_schema = 'main'
                            ORDER BY table_name
                        """))
                        all_tables = [row[0] for row in result]
                    except Exception as e:
                        logger.debug(f"DuckDB information_schema query failed: {e}")
                        # Fallback: use SHOW TABLES
                        try:
                            result = conn.execute(text("SHOW TABLES"))
                            all_tables = [row[0] for row in result]
                        except Exception:
                            all_tables = []
                else:
                    # For PostgreSQL, MySQL - use standard information_schema with BASE TABLE filter
                    try:
                        result = conn.execute(text("""
                            SELECT table_name 
                            FROM information_schema.tables 
                            WHERE table_type = 'BASE TABLE'
                            AND table_schema NOT IN ('pg_catalog', 'information_schema')
                            ORDER BY table_name
                        """))
                        all_tables = [row[0] for row in result]
                    except Exception:
                        try:
                            result = conn.execute(text("SHOW TABLES"))
                            all_tables = [row[0] for row in result]
                        except Exception:
                            all_tables = []
                
                # Filter out internal/metadata tables (those starting with underscore)
                self._table_names = [t for t in all_tables if not t.startswith('_')]
                
                # Log what was found
                if all_tables:
                    filtered_count = len(all_tables) - len(self._table_names)
                    if filtered_count > 0:
                        logger.debug(f"Filtered out {filtered_count} internal tables")
            
            logger.info(f"Discovered {len(self._table_names)} tables: {self._table_names}")
            return self._table_names
            
        except Exception as e:
            logger.error(f"Failed to discover tables: {e}")
            return []
    
    def get_schema_context(self, max_tables: int = 10) -> str:
        """
        Get database schema as context for LLM queries.
        
        Returns a formatted string describing tables and their columns with types.
        Highlights VARCHAR columns that contain date-like names and need casting.
        """
        if self._cached_schema:
            return self._cached_schema
        
        tables = self._discover_tables()[:max_tables]
        engine = self._get_engine()
        
        schema_parts = []
        varchar_date_columns = []  # Track VARCHAR columns that look like dates
        
        # Date-related column name patterns
        date_patterns = ['date', 'time', 'created', 'updated', 'modified', 'timestamp', '_at', '_on']
        
        try:
            with engine.connect() as conn:
                for table in tables:
                    try:
                        # Get column info
                        result = conn.execute(text(f"""
                            SELECT column_name, data_type, is_nullable
                            FROM information_schema.columns
                            WHERE table_name = :table
                            ORDER BY ordinal_position
                        """), {"table": table})
                        
                        columns = [(row[0], row[1], row[2]) for row in result]
                        
                        if columns:
                            col_parts = []
                            for name, dtype, nullable in columns[:30]:
                                null_indicator = "?" if nullable == 'YES' else ""
                                col_parts.append(f"{name} ({dtype}{null_indicator})")
                                
                                # Check if this is a VARCHAR column with a date-like name
                                if dtype.upper() == 'VARCHAR':
                                    name_lower = name.lower()
                                    if any(pattern in name_lower for pattern in date_patterns):
                                        varchar_date_columns.append(f"{table}.{name}")
                            
                            col_desc = ", ".join(col_parts)
                            if len(columns) > 30:
                                col_desc += f", ... and {len(columns) - 30} more columns"
                            schema_parts.append(f"- {table}: {col_desc}")
                    except Exception:
                        schema_parts.append(f"- {table}: (columns unavailable)")
            
            # Build final schema with warnings
            final_parts = ["Tables:\n" + "\n".join(schema_parts)]
            
            # Add explicit warning about VARCHAR date columns
            if varchar_date_columns:
                warning = "\n\nWARNING - VARCHAR DATE COLUMNS REQUIRE CASTING:\n"
                warning += "These columns store dates as VARCHAR. You MUST cast them before date operations:\n"
                for col in varchar_date_columns:
                    col_name = col.split('.')[-1]
                    warning += f"  - {col} -> CAST({col_name} AS TIMESTAMP)\n"
                warning += "\nREQUIRED PATTERNS:\n"
                warning += "  WHERE CAST(created_at AS TIMESTAMP) >= CURRENT_DATE - INTERVAL '1 year'\n"
                warning += "  DATE_TRUNC('month', CAST(created_at AS TIMESTAMP))"
                final_parts.append(warning)
            
            self._cached_schema = "\n".join(final_parts)
            return self._cached_schema
            
        except Exception as e:
            logger.error(f"Failed to get schema context: {e}")
            return f"Tables: {', '.join(tables)}"


    async def get_semantic_schema_context(
        self,
        query: str,
        top_k: int = 5,
    ) -> str:
        """
        Get semantically relevant schema context for a specific query using vector search.
        
        Instead of blindly loading the first N tables, this method uses the SchemaRetriever
        to fetch only the tables that are semantically relevant to the user's query.
        Falls back to blind loading if vector search is not available.
        
        Args:
            query: The natural language query to find relevant tables for
            top_k: Number of relevant tables to retrieve (default 5)
            
        Returns:
            Formatted DDL context string with relevant tables
        """
        # Try semantic retrieval if config_id is available
        if self._config_id:
            try:
                from app.modules.embeddings.schema_retriever import get_ddl_context_for_sql
                
                # Use vector search to get relevant table DDLs
                ddl_context = await get_ddl_context_for_sql(
                    query=query,
                    config_id=self._config_id,
                    top_k=top_k,
                    compact=False,
                )
                
                if ddl_context and ddl_context.strip():
                    logger.info(f"Retrieved semantic schema context for query (top_k={top_k})")
                    return ddl_context
                else:
                    logger.warning("Semantic schema retrieval returned empty, falling back to blind loading")
                    
            except ImportError as e:
                logger.warning(f"SchemaRetriever not available, falling back to blind loading: {e}")
            except Exception as e:
                logger.warning(f"Semantic schema retrieval failed, falling back to blind loading: {e}")
        
        # Fallback: use traditional blind schema loading
        logger.debug("Using fallback blind schema loading (no config_id or semantic retrieval failed)")
        return self.get_schema_context(max_tables=top_k)

    @property
    def cached_schema(self) -> str:
        """Get cached schema or generate it."""
        return self.get_schema_context()
    
    def execute_query(self, sql: str, timeout_seconds: int = 30) -> Tuple[List[Dict[str, Any]], int]:
        """
        Execute a SQL query and return results.
        
        Args:
            sql: SQL query to execute
            timeout_seconds: Query timeout in seconds (default 30s)
            
        Returns:
            Tuple of (results as list of dicts, total row count)
        """
        engine = self._get_engine()
        
        # Do NOT add automatic LIMIT - data analysts need full results
        # If user wants a limit, they will specify it in their question
        
        try:
            with engine.connect() as conn:
                # Set statement timeout for PostgreSQL to prevent long-running queries
                if not self._is_duckdb():
                    try:
                        conn.execute(text(f"SET statement_timeout = '{timeout_seconds}s'"))
                    except Exception as e:
                        logger.debug(f"Could not set statement_timeout: {e}")
                
                result = conn.execute(text(sql))
                rows = result.fetchall()
                columns = result.keys()
                
                # Convert to list of dicts
                results = [dict(zip(columns, row)) for row in rows]
                
                logger.info(f"Query executed", rows=len(results), sql=sql[:100])
                return results, len(results)
                
        except Exception as e:
            error_str = str(e)
            # Provide helpful message for timeout errors
            if "canceling statement due to statement timeout" in error_str.lower() or "timeout" in error_str.lower():
                logger.warning(f"Query timed out after {timeout_seconds}s", sql=sql[:200])
                raise TimeoutError(
                    f"Query timed out after {timeout_seconds} seconds. "
                    f"The query may be too complex or the table too large. "
                    f"Try adding filters (WHERE clause) or limiting results (LIMIT)."
                )
            logger.error(f"Query execution failed: {e}", sql=sql[:200])
            raise
    
    def _format_results(self, results: List[Dict[str, Any]], count: int) -> str:
        """Format query results for response."""
        if not results:
            return "No results found for your query."
        
        # Format as readable text
        if count == 1 and len(results[0]) == 1:
            # Single value result
            value = list(results[0].values())[0]
            return f"Result: {value}"
        
        # Multiple rows - format as markdown table
        if results:
            headers = list(results[0].keys())
            header_row = " | ".join(str(h) for h in headers)
            separator = " | ".join("-" * len(str(h)) for h in headers)
            
            data_rows = []
            for row in results[:20]:  # Limit display rows
                data_rows.append(" | ".join(str(v) for v in row.values()))
            
            table = f"{header_row}\n{separator}\n" + "\n".join(data_rows)
            
            if count > 20:
                table += f"\n\n... and {count - 20} more rows"
            
            return table
        
        return "Query executed but returned no data."
    
    async def query_async(
        self,
        natural_language_query: str,
        max_retries: int = 3,
    ) -> str:
        """
        Execute a natural language query using LLM to generate SQL (async version).
        
        This is the main entry point for Intent A (SQL-only) queries with few-shot learning.
        Includes relevance checking to filter out irrelevant queries early.
        Implements retry logic: if SQL execution fails, the error is appended to the
        prompt and the LLM is asked to fix the query (up to max_retries attempts).
        
        Args:
            natural_language_query: User's question in natural language
            max_retries: Maximum number of retry attempts (default 3)
            
        Returns:
            Formatted response string with query results
            
        Raises:
            IrrelevantQueryException: If query is not relevant to the database
        """
        from app.core.llm import create_llm_provider
        from langchain_core.prompts import ChatPromptTemplate
        
        # Check query relevance first (if enabled)
        if self._enable_relevance_check and self._relevance_checker:
            table_names = self._discover_tables()
            is_relevant, classification = self._relevance_checker.check(
                question=natural_language_query,
                table_names=table_names
            )
            
            # Update statistics (without logging query content for privacy)
            _relevance_stats["total_checked"] += 1
            
            if not is_relevant:
                if classification == IRRELEVANT_PII or "<IRRELEVANT:PII>" in classification:
                    _relevance_stats["rejected_pii"] += 1
                    logger.info(
                        "Query rejected: PII request (total_checked=%d, rejected_pii=%d)",
                        _relevance_stats["total_checked"],
                        _relevance_stats["rejected_pii"]
                    )
                    raise IrrelevantQueryException(
                        "This query requests personally identifiable information which cannot be disclosed for privacy reasons.",
                        "<IRRELEVANT:PII>"
                    )
                elif classification == IRRELEVANT_CONTEXT or "<IRRELEVANT:CONTEXT>" in classification:
                    _relevance_stats["rejected_context"] += 1
                    logger.info(
                        "Query rejected: out of context (total_checked=%d, rejected_context=%d)",
                        _relevance_stats["total_checked"],
                        _relevance_stats["rejected_context"]
                    )
                    raise IrrelevantQueryException(
                        "This question cannot be answered using the available data. Please ask about topics covered in the database.",
                        "<IRRELEVANT:CONTEXT>"
                    )
                else:
                    _relevance_stats["rejected_syntax"] += 1
                    logger.info(
                        "Query rejected: syntax/other (total_checked=%d, rejected_syntax=%d)",
                        _relevance_stats["total_checked"],
                        _relevance_stats["rejected_syntax"]
                    )
                    raise IrrelevantQueryException(
                        "Unable to process this query. Please rephrase as a clear question about the data.",
                        classification
                    )
            else:
                _relevance_stats["passed"] += 1
                logger.debug(
                    "Query passed relevance check (total_checked=%d, passed=%d)",
                    _relevance_stats["total_checked"],
                    _relevance_stats["passed"]
                )
        
        # Use semantic schema retrieval based on the query (not blind loading)
        schema = await self.get_semantic_schema_context(
            query=natural_language_query,
            top_k=5,  # Retrieve top 5 most relevant tables
        )
        
        # Get few-shot examples
        few_shot_examples = []
        few_shot_section = ""
        if self._enable_few_shot and self._sql_examples_store:
            few_shot_examples = await self._get_few_shot_examples(
                question=natural_language_query,
                top_k=3,
                min_score=0.5
            )
            few_shot_section = self._format_few_shot_examples(few_shot_examples)
            logger.info(f"Using {len(few_shot_examples)} few-shot examples for SQL generation")
        
        # Build the enhanced prompt with DuckDB rules, data dictionary, and few-shot examples
        base_prompt = get_sql_generator_prompt()
        
        # Add DuckDB-specific rules if using DuckDB
        db_rules = DUCKDB_SQL_RULES if self._is_duckdb() else ""
        
        # Get data dictionary context for semantic enrichment
        data_dict_context = self._get_data_dictionary_context()
        
        system_prompt_parts = [base_prompt]
        if db_rules:
            system_prompt_parts.append(db_rules)
        if data_dict_context:
            system_prompt_parts.append(data_dict_context)
        if few_shot_section:
            system_prompt_parts.append(few_shot_section)
        system_prompt_parts.append("Database Schema:\n{schema}")
        
        full_system_prompt = "\n\n".join(system_prompt_parts)
        
        # Create LLM provider
        try:
            provider = create_llm_provider("openai", {
                "model": "gpt-4o-mini",
                "temperature": 0,
            })
            llm = provider.get_langchain_llm()
        except Exception as e:
            logger.error(f"Failed to create LLM provider: {e}")
            return f"Failed to initialize LLM: {str(e)}"
        
        # =========================================================================
        # RETRY LOOP: Generate SQL, execute, retry on error with error feedback
        # =========================================================================
        previous_error: Optional[str] = None
        last_sql: Optional[str] = None
        
        for attempt in range(max_retries):
            try:
                # Build prompt - include previous error if this is a retry
                if previous_error and last_sql:
                    # Add error context for retry attempts
                    error_context = f"""

PREVIOUS ATTEMPT FAILED:
SQL that failed:
```sql
{last_sql}
```

Previous Error: {previous_error}

Please fix the SQL query to resolve this error. Generate ONLY the corrected SQL.
"""
                    retry_prompt = ChatPromptTemplate.from_messages([
                        ("system", full_system_prompt + error_context),
                        ("user", "{question}")
                    ])
                    chain = retry_prompt | llm
                    logger.info(f"Retry attempt {attempt + 1}/{max_retries} with error feedback")
                else:
                    # First attempt - normal prompt
                    prompt = ChatPromptTemplate.from_messages([
                        ("system", full_system_prompt),
                        ("user", "{question}")
                    ])
                    chain = prompt | llm
                
                # Generate SQL using LLM
                response = chain.invoke({
                    "schema": schema,
                    "question": natural_language_query
                })
                
                # Extract SQL from response (remove markdown code blocks if present)
                sql = response.content.strip()
                sql = re.sub(r'^```sql\s*', '', sql)
                sql = re.sub(r'^```\s*', '', sql)
                sql = re.sub(r'\s*```$', '', sql)
                sql = sql.strip()
                last_sql = sql
                
                logger.info("LLM generated SQL", attempt=attempt + 1, generated_sql=sql, question=natural_language_query[:100])
                
                # Execute the generated SQL using read-only session
                results, count = self.execute_query(sql)
                
                # Success! Format and return results
                logger.info(f"Query succeeded on attempt {attempt + 1}")
                return self._format_results(results, count)
                
            except Exception as e:
                error_str = str(e)
                previous_error = error_str
                
                logger.warning(
                    f"SQL execution failed on attempt {attempt + 1}/{max_retries}: {error_str[:200]}"
                )
                
                # If this was the last attempt, return error
                if attempt == max_retries - 1:
                    logger.error(
                        f"All {max_retries} attempts failed. Last error: {error_str}"
                    )
                    return f"Failed to execute query after {max_retries} attempts. Last error: {error_str}"
                
                # Otherwise, continue to next iteration with error feedback
                continue
        
        # Should not reach here, but just in case
        return f"Failed to execute query: Unknown error after {max_retries} attempts"
    
    def query(self, natural_language_query: str) -> str:
        """
        Execute a natural language query using LLM to generate SQL.
        
        This is the synchronous version that wraps the async implementation.
        For new code, prefer using query_async() directly.
        
        Args:
            natural_language_query: User's question in natural language
            
        Returns:
            Formatted response string with query results
        """
        # Try to use existing event loop, or create a new one
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                # We're already in an async context, create new loop in thread
                import concurrent.futures
                with concurrent.futures.ThreadPoolExecutor() as executor:
                    future = executor.submit(asyncio.run, self.query_async(natural_language_query))
                    return future.result(timeout=60)
            else:
                return loop.run_until_complete(self.query_async(natural_language_query))
        except RuntimeError:
            # No event loop, create a new one
            return asyncio.run(self.query_async(natural_language_query))
    
    def run(self, sql: str) -> str:
        """
        Execute raw SQL and return results as a string.
        
        Used for Intent C SQL filters.
        """
        try:
            results, count = self.execute_query(sql)
            return str(results)
        except Exception as e:
            return f"Error: {str(e)}"




class SQLServiceForCSV(SQLService):
    """
    SQL Service that queries CSV files directly using DuckDB's read_csv_auto.
    
    This is used when a file data source doesn't have a pre-built DuckDB database,
    allowing queries against the raw CSV file.
    """
    
    def __init__(
        self,
        csv_path: str,
        table_name: str = "data",
        max_result_rows: int = 100,
        enable_few_shot: bool = True,
    ):
        """
        Initialize CSV SQL service.
        
        Args:
            csv_path: Path to the CSV file
            table_name: Virtual table name for the CSV (used in queries)
            max_result_rows: Maximum rows to return
            enable_few_shot: Enable few-shot example retrieval
        """
        self._csv_path = csv_path
        self._table_name = table_name
        self._max_result_rows = max_result_rows
        self._cached_schema: Optional[str] = None
        self._settings = get_settings()
        self._enable_few_shot = enable_few_shot
        self._engine = None
        self._table_names = [table_name]
        
        # Use in-memory DuckDB that reads from CSV
        self._db_url = ":memory:"
        
        # Initialize SQL examples store for few-shot learning
        self._sql_examples_store: Optional[SQLExamplesStore] = None
        if enable_few_shot:
            try:
                self._sql_examples_store = get_sql_examples_store()
            except Exception as e:
                logger.warning(f"Failed to initialize SQL examples store: {e}")
    
    def _is_duckdb(self) -> bool:
        """This is always DuckDB."""
        return True
    
    def _get_engine(self) -> Engine:
        """Get DuckDB engine - creates a view for the CSV file."""
        if self._engine is not None:
            return self._engine
        
        import duckdb
        
        try:
            # Create in-memory DuckDB connection
            self._engine = create_engine("duckdb:///:memory:")
            
            # Create a view that reads from the CSV file
            csv_path_escaped = self._csv_path.replace("'", "''")
            with self._engine.connect() as conn:
                conn.execute(text(f"""
                    CREATE OR REPLACE VIEW {self._table_name} AS 
                    SELECT * FROM read_csv_auto('{csv_path_escaped}', header=true)
                """))
                conn.commit()
            
            logger.info(f"Created DuckDB view '{self._table_name}' for CSV: {self._csv_path}")
            return self._engine
            
        except Exception as e:
            logger.error(f"Failed to create DuckDB engine for CSV: {e}")
            raise
    
    def _discover_tables(self) -> List[str]:
        """Return the virtual table name for this CSV."""
        return [self._table_name]
    
    def get_schema_context(self, max_tables: int = 10) -> str:
        """Get schema by inspecting the CSV file structure."""
        if self._cached_schema:
            return self._cached_schema
        
        try:
            import duckdb
            
            csv_path_escaped = self._csv_path.replace("'", "''")
            conn = duckdb.connect(":memory:")
            
            # Get column info using DESCRIBE
            result = conn.execute(f"""
                DESCRIBE SELECT * FROM read_csv_auto('{csv_path_escaped}', header=true, sample_size=1000)
            """).fetchall()
            conn.close()
            
            columns = []
            for row in result:
                col_name = row[0]
                col_type = str(row[1]) if row[1] else "VARCHAR"
                columns.append(f"{col_name} ({col_type})")
            
            col_desc = ", ".join(columns[:30])  # Limit to 30 columns for prompt
            self._cached_schema = f"Tables:\n- {self._table_name}: {col_desc}"
            
            logger.info(f"Discovered {len(columns)} columns in CSV")
            return self._cached_schema
            
        except Exception as e:
            logger.error(f"Failed to get CSV schema: {e}")
            return f"Tables: {self._table_name}"
    
    def execute_query(self, sql: str) -> Tuple[List[Dict[str, Any]], int]:
        """Execute SQL query against the CSV file."""
        import duckdb
        
        # Do NOT add automatic LIMIT - data analysts need full results
        # If user wants a limit, they will specify it in their question
        
        try:
            csv_path_escaped = self._csv_path.replace("'", "''")
            conn = duckdb.connect(":memory:")
            
            # Create view for the CSV
            conn.execute(f"""
                CREATE OR REPLACE VIEW {self._table_name} AS 
                SELECT * FROM read_csv_auto('{csv_path_escaped}', header=true)
            """)
            
            # Execute the query
            result = conn.execute(sql)
            rows = result.fetchall()
            columns = [desc[0] for desc in result.description]
            conn.close()
            
            # Convert to list of dicts
            results = [dict(zip(columns, row)) for row in rows]
            
            logger.info(f"CSV query executed", rows=len(results), sql=sql[:100])
            return results, len(results)
            
        except Exception as e:
            logger.error(f"CSV query execution failed: {e}", sql=sql[:200])
            raise


class SQLServiceFactory:
    """Factory for creating SQLService instances from data sources."""
    
    @staticmethod
    async def from_data_source_id(
        data_source_id: UUID,
        db_session,
        enable_few_shot: bool = True,
        config_id: Optional[int] = None,
        agent_id: Optional[str] = None,
    ) -> Optional[SQLService]:
        """
        Create a SQLService from a data source ID.
        
        Args:
            data_source_id: UUID of the data source
            db_session: Async SQLAlchemy session
            enable_few_shot: Enable few-shot example retrieval
            config_id: Optional agent config ID for semantic schema retrieval
            agent_id: Optional agent ID for per-agent SQL examples and data dictionary
            
        Returns:
            SQLService instance or None if not found
        """
        from sqlalchemy import select
        from app.modules.data_sources.models import DataSourceModel
        
        try:
            stmt = select(DataSourceModel).where(DataSourceModel.id == data_source_id)
            result = await db_session.execute(stmt)
            data_source = result.scalar_one_or_none()
            
            if not data_source:
                logger.warning(f"Data source not found: {data_source_id}")
                return None
            
            logger.debug(f"Data source found: id={data_source_id}, type={data_source.source_type}")
            
            if data_source.source_type == "database":
                # Decrypt the database URL if encrypted
                db_url = data_source.db_url
                if db_url and db_url.startswith("encrypted:"):
                    db_url = decrypt_value(db_url)
                
                if not db_url:
                    logger.warning(f"Data source {data_source_id} has no db_url configured")
                    return None
                    
                return SQLService(db_url=db_url, enable_few_shot=enable_few_shot, config_id=config_id, agent_id=agent_id)
                
            elif data_source.source_type == "file":
                # Use DuckDB for file-based data sources
                duckdb_path = data_source.duckdb_file_path
                if duckdb_path:
                    return SQLService(
                        db_url=f"duckdb://{duckdb_path}",
                        enable_few_shot=enable_few_shot,
                        config_id=config_id,
                        agent_id=agent_id,
                    )
                
                # Fallback: Create DuckDB service that reads CSV directly
                # This handles cases where duckdb_file_path is null but we have the original CSV
                if data_source.original_file_path:
                    logger.info(f"Creating DuckDB service for CSV file: {data_source.original_file_path}")
                    return SQLServiceForCSV(
                        csv_path=data_source.original_file_path,
                        table_name=data_source.duckdb_table_name or "data",
                        enable_few_shot=enable_few_shot
                    )
                
                logger.warning(f"File data source {data_source_id} has no duckdb_file_path or original_file_path")
                return None
                    
            logger.warning(f"Data source type not supported: {data_source.source_type}")
            return None
            
        except Exception as e:
            logger.error(f"Failed to create SQL service: {e}", exc_info=True)
            return None
    
    @staticmethod
    async def from_agent_config(
        agent_id: UUID,
        db_session,
        enable_few_shot: bool = True
    ) -> Optional[SQLService]:
        """
        Create a SQLService from an agent's active configuration.
        
        Gets the data source from the agent's active config.
        """
        from sqlalchemy import select
        from app.modules.agents.models import AgentConfigModel
        
        try:
            # Get the active config for the agent
            stmt = select(AgentConfigModel).where(
                AgentConfigModel.agent_id == agent_id,
                AgentConfigModel.is_active == 1
            )
            result = await db_session.execute(stmt)
            config = result.scalar_one_or_none()
            
            if not config:
                logger.warning(f"No active config found for agent: {agent_id}")
                return None
            
            logger.debug(f"Agent config found: id={config.id}, data_source_id={config.data_source_id}")
            
            if not config.data_source_id:
                logger.warning(f"Agent config has no data_source_id")
                return None
            
            return await SQLServiceFactory.from_data_source_id(
                config.data_source_id,
                db_session,
                enable_few_shot=enable_few_shot,
                config_id=config.id,  # Pass config ID for semantic schema retrieval
                agent_id=str(agent_id),  # Pass agent ID for per-agent SQL examples
            )
            
        except Exception as e:
            logger.error(f"Failed to create SQL service from agent config: {e}", exc_info=True)
            return None
