"""
SQL Test Runner - Automated NL2SQL accuracy evaluation against golden datasets.

This script runs natural language to SQL tests against a database and generates
reports on accuracy, execution success, and regression detection.

Run with:
    python -m app.scripts.run_sql_tests --input tests.csv --output report.md
    python -m app.scripts.run_sql_tests --filter "temporal_*" --verbose
    python -m app.scripts.run_sql_tests --input tests.json --db-url "duckdb://data/test.db"

Features:
    - Loads test cases from CSV or JSON files
    - Generates SQL using the SQLService
    - Executes and compares results
    - Tracks execution time and errors
    - Generates detailed reports
    - Privacy-safe logging (no PII in logs)

IMPORTANT: This script does NOT log actual data results to avoid PII exposure.
Only metadata (row counts, column names, execution status) is logged.
"""
import asyncio
import argparse
import csv
import json
import re
import sys
import os
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from collections import defaultdict

# Add parent to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from app.core.utils.logging import get_logger, configure_logging
from app.core.settings import get_settings
from app.modules.chat.sql_service import SQLService, SQLServiceForCSV

logger = get_logger(__name__)


# ============================================
# Data Classes
# ============================================

class TestStatus(Enum):
    """Status of a test execution."""
    PASSED = "passed"
    FAILED = "failed"
    ERROR = "error"
    SKIPPED = "skipped"


@dataclass
class TestCase:
    """
    A single test case for NL2SQL evaluation.
    
    Attributes:
        test_id: Unique identifier for the test
        question: Natural language question to convert to SQL
        expected_sql: Optional expected SQL (for reference, not exact match)
        expected_result_contains: List of strings expected in result
        expected_row_count: Expected number of rows (if known)
        tags: List of tags for categorization and filtering
        description: Optional description of what the test validates
        skip: Whether to skip this test
        skip_reason: Reason for skipping
    """
    test_id: str
    question: str
    expected_sql: Optional[str] = None
    expected_result_contains: List[str] = field(default_factory=list)
    expected_row_count: Optional[int] = None
    tags: List[str] = field(default_factory=list)
    description: str = ""
    skip: bool = False
    skip_reason: str = ""
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'TestCase':
        """Create a TestCase from a dictionary."""
        # Handle tags as comma-separated string or list
        tags = data.get('tags', [])
        if isinstance(tags, str):
            tags = [t.strip() for t in tags.split(',') if t.strip()]
        
        # Handle expected_result_contains
        expected_contains = data.get('expected_result_contains', [])
        if isinstance(expected_contains, str):
            expected_contains = [s.strip() for s in expected_contains.split(',') if s.strip()]
        
        return cls(
            test_id=str(data.get('test_id', data.get('id', 'unknown'))),
            question=data.get('question', data.get('query', data.get('natural_language', ''))),
            expected_sql=data.get('expected_sql', data.get('sql', data.get('ground_truth'))),
            expected_result_contains=expected_contains,
            expected_row_count=data.get('expected_row_count'),
            tags=tags,
            description=data.get('description', ''),
            skip=data.get('skip', False),
            skip_reason=data.get('skip_reason', '')
        )


@dataclass
class TestResult:
    """
    Result of executing a single test case.
    
    Attributes:
        test_id: Test case identifier
        question: The natural language question (for reference)
        status: Overall test status
        generated_sql: SQL generated by the system
        expected_sql: Expected SQL (if provided)
        sql_executed: Whether the SQL executed successfully
        sql_error: Error message if execution failed
        result_match: Whether results matched expectations
        row_count: Number of rows returned
        column_names: Names of columns in result (sanitized)
        execution_time_ms: Time to generate and execute SQL
        generation_time_ms: Time to generate SQL only
        notes: Additional notes about the test
        tags: Tags from the test case
    """
    test_id: str
    question: str
    status: TestStatus
    generated_sql: str = ""
    expected_sql: Optional[str] = None
    sql_executed: bool = False
    sql_error: Optional[str] = None
    result_match: bool = False
    row_count: int = 0
    column_names: List[str] = field(default_factory=list)
    execution_time_ms: float = 0.0
    generation_time_ms: float = 0.0
    notes: str = ""
    tags: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        d = asdict(self)
        d['status'] = self.status.value
        return d


@dataclass
class TestReport:
    """
    Aggregate report of all test results.
    
    Attributes:
        timestamp: When the tests were run
        total_tests: Total number of tests
        passed: Number of passed tests
        failed: Number of failed tests
        errors: Number of tests with errors
        skipped: Number of skipped tests
        pass_rate: Percentage of passed tests
        results: List of individual test results
        errors_by_type: Errors grouped by type
        results_by_tag: Results grouped by tag
        execution_stats: Execution time statistics
    """
    timestamp: str
    total_tests: int
    passed: int
    failed: int
    errors: int
    skipped: int
    pass_rate: float
    results: List[TestResult]
    errors_by_type: Dict[str, List[str]] = field(default_factory=dict)
    results_by_tag: Dict[str, Dict[str, int]] = field(default_factory=dict)
    execution_stats: Dict[str, float] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            'timestamp': self.timestamp,
            'total_tests': self.total_tests,
            'passed': self.passed,
            'failed': self.failed,
            'errors': self.errors,
            'skipped': self.skipped,
            'pass_rate': self.pass_rate,
            'results': [r.to_dict() for r in self.results],
            'errors_by_type': self.errors_by_type,
            'results_by_tag': self.results_by_tag,
            'execution_stats': self.execution_stats
        }


# ============================================
# SQL Test Runner
# ============================================

class SQLTestRunner:
    """
    Automated test runner for NL2SQL evaluation.
    
    Executes test cases against a SQL service and generates reports.
    
    Usage:
        runner = SQLTestRunner(sql_service, test_cases)
        results = await runner.run_all()
        report = runner.generate_report(results)
    """
    
    def __init__(
        self,
        sql_service: SQLService,
        test_cases: List[TestCase],
        verbose: bool = False,
        skip_relevance_check: bool = True
    ):
        """
        Initialize the test runner.
        
        Args:
            sql_service: SQLService instance for query execution
            test_cases: List of test cases to run
            verbose: Enable verbose output
            skip_relevance_check: Skip query relevance checking for tests
        """
        self.sql_service = sql_service
        self.test_cases = test_cases
        self.verbose = verbose
        self.skip_relevance_check = skip_relevance_check
        
        # Disable relevance checking for tests to allow all queries
        if skip_relevance_check:
            self.sql_service._enable_relevance_check = False
    
    async def run_all(self) -> List[TestResult]:
        """
        Run all test cases.
        
        Returns:
            List of TestResult objects
        """
        results = []
        total = len(self.test_cases)
        
        logger.info(f"Starting test run: {total} test cases")
        
        for i, test_case in enumerate(self.test_cases, 1):
            if self.verbose:
                print(f"[{i}/{total}] Running test: {test_case.test_id}")
            
            result = await self.run_single(test_case)
            results.append(result)
            
            # Log progress (without query content)
            status_symbol = {
                TestStatus.PASSED: "✓",
                TestStatus.FAILED: "✗",
                TestStatus.ERROR: "!",
                TestStatus.SKIPPED: "-"
            }.get(result.status, "?")
            
            if self.verbose:
                print(f"  {status_symbol} {result.status.value} ({result.execution_time_ms:.0f}ms)")
            
            logger.debug(
                f"Test {i}/{total} complete: id={test_case.test_id}, "
                f"status={result.status.value}, time_ms={result.execution_time_ms:.0f}"
            )
        
        # Summary
        passed = sum(1 for r in results if r.status == TestStatus.PASSED)
        failed = sum(1 for r in results if r.status == TestStatus.FAILED)
        errors = sum(1 for r in results if r.status == TestStatus.ERROR)
        skipped = sum(1 for r in results if r.status == TestStatus.SKIPPED)
        
        logger.info(
            f"Test run complete: {passed} passed, {failed} failed, "
            f"{errors} errors, {skipped} skipped"
        )
        
        return results
    
    async def run_single(self, test_case: TestCase) -> TestResult:
        """
        Run a single test case.
        
        Args:
            test_case: TestCase to execute
            
        Returns:
            TestResult with execution details
        """
        # Handle skipped tests
        if test_case.skip:
            return TestResult(
                test_id=test_case.test_id,
                question=test_case.question[:100],  # Truncate for privacy
                status=TestStatus.SKIPPED,
                notes=test_case.skip_reason or "Marked as skip",
                tags=test_case.tags
            )
        
        start_time = time.time()
        generation_start = start_time
        
        try:
            # Generate SQL from natural language
            generated_sql = await self._generate_sql(test_case.question)
            generation_time = (time.time() - generation_start) * 1000
            
            if not generated_sql:
                return TestResult(
                    test_id=test_case.test_id,
                    question=test_case.question[:100],
                    status=TestStatus.ERROR,
                    sql_error="Failed to generate SQL",
                    generation_time_ms=generation_time,
                    execution_time_ms=(time.time() - start_time) * 1000,
                    notes="SQL generation returned empty result",
                    tags=test_case.tags
                )
            
            # Execute the generated SQL
            # Track execution (timing already captured in start_time)
            try:
                results, row_count = self.sql_service.execute_query(generated_sql)
                sql_executed = True
                sql_error = None
                column_names = list(results[0].keys()) if results else []
            except Exception as e:
                sql_executed = False
                sql_error = self._sanitize_error(str(e))
                results = []
                row_count = 0
                column_names = []
            
            execution_time = (time.time() - start_time) * 1000
            
            # Check if results match expectations
            result_match, match_notes = self._check_result_match(
                test_case, results, row_count, column_names
            )
            
            # Determine overall status
            if not sql_executed:
                status = TestStatus.ERROR
            elif result_match:
                status = TestStatus.PASSED
            else:
                status = TestStatus.FAILED
            
            return TestResult(
                test_id=test_case.test_id,
                question=test_case.question[:100],  # Truncate for privacy
                status=status,
                generated_sql=generated_sql,
                expected_sql=test_case.expected_sql,
                sql_executed=sql_executed,
                sql_error=sql_error,
                result_match=result_match,
                row_count=row_count,
                column_names=column_names[:10],  # Limit column names
                execution_time_ms=execution_time,
                generation_time_ms=generation_time,
                notes=match_notes,
                tags=test_case.tags
            )
            
        except Exception as e:
            execution_time = (time.time() - start_time) * 1000
            return TestResult(
                test_id=test_case.test_id,
                question=test_case.question[:100],
                status=TestStatus.ERROR,
                sql_error=self._sanitize_error(str(e)),
                execution_time_ms=execution_time,
                notes=f"Unexpected error: {type(e).__name__}",
                tags=test_case.tags
            )
    
    async def _generate_sql(self, question: str) -> str:
        """
        Generate SQL from a natural language question.
        
        Args:
            question: Natural language question
            
        Returns:
            Generated SQL query
        """
        from app.core.llm import create_llm_provider
        from langchain_core.prompts import ChatPromptTemplate
        from app.core.prompts import get_sql_generator_prompt
        
        schema = self.sql_service.get_schema_context()
        base_prompt = get_sql_generator_prompt()
        
        # Add DuckDB rules if applicable
        db_rules = ""
        if hasattr(self.sql_service, '_is_duckdb') and self.sql_service._is_duckdb():
            from app.modules.chat.sql_service import DUCKDB_SQL_RULES
            db_rules = DUCKDB_SQL_RULES
        
        # Get few-shot examples if available
        few_shot_section = ""
        if hasattr(self.sql_service, '_sql_examples_store') and self.sql_service._sql_examples_store:
            try:
                examples = await self.sql_service._get_few_shot_examples(question, top_k=3)
                few_shot_section = self.sql_service._format_few_shot_examples(examples)
            except Exception:
                pass
        
        # Build prompt
        system_prompt_parts = [base_prompt]
        if db_rules:
            system_prompt_parts.append(db_rules)
        if few_shot_section:
            system_prompt_parts.append(few_shot_section)
        system_prompt_parts.append("Database Schema:\n{schema}")
        
        full_system_prompt = "\n\n".join(system_prompt_parts)
        
        prompt = ChatPromptTemplate.from_messages([
            ("system", full_system_prompt),
            ("user", "{question}")
        ])
        
        provider = create_llm_provider("openai", {
            "model": "gpt-4o-mini",
            "temperature": 0,
        })
        llm = provider.get_langchain_llm()
        
        chain = prompt | llm
        response = chain.invoke({
            "schema": schema,
            "question": question
        })
        
        # Extract SQL from response
        sql = response.content.strip()
        sql = re.sub(r'^```sql\s*', '', sql)
        sql = re.sub(r'\s*```$', '', sql)
        
        return sql
    
    def _check_result_match(
        self,
        test_case: TestCase,
        results: List[Dict[str, Any]],
        row_count: int,
        column_names: List[str]
    ) -> Tuple[bool, str]:
        """
        Check if results match test case expectations.
        
        PRIVACY NOTE: This method does NOT log actual data values.
        
        Args:
            test_case: The test case with expectations
            results: Query results (not logged)
            row_count: Number of rows returned
            column_names: Column names in results
            
        Returns:
            Tuple of (match_success, notes)
        """
        notes_parts = []
        all_matched = True
        
        # Check row count if expected
        if test_case.expected_row_count is not None:
            if row_count != test_case.expected_row_count:
                all_matched = False
                notes_parts.append(
                    f"Row count mismatch: got {row_count}, expected {test_case.expected_row_count}"
                )
            else:
                notes_parts.append(f"Row count matched: {row_count}")
        
        # Check if expected strings are in results (by converting to string representation)
        # NOTE: We check but do NOT log the actual values for privacy
        if test_case.expected_result_contains:
            results_str = str(results).lower()
            missing = []
            for expected in test_case.expected_result_contains:
                if expected.lower() not in results_str:
                    missing.append(expected)
            
            if missing:
                all_matched = False
                notes_parts.append(f"Missing expected values: {len(missing)} of {len(test_case.expected_result_contains)}")
            else:
                notes_parts.append(f"All {len(test_case.expected_result_contains)} expected values found")
        
        # If no specific expectations, consider it passed if SQL executed
        if not test_case.expected_row_count and not test_case.expected_result_contains:
            if row_count > 0:
                notes_parts.append(f"Query returned {row_count} rows")
            else:
                notes_parts.append("Query executed but returned no rows")
            # Consider it passed if it executed without error
            all_matched = True
        
        return all_matched, "; ".join(notes_parts)
    
    def _sanitize_error(self, error: str) -> str:
        """
        Sanitize error message to remove potential PII.
        
        Args:
            error: Raw error message
            
        Returns:
            Sanitized error message
        """
        # Remove potential data values from error messages
        # Pattern: remove quoted strings that look like data
        sanitized = re.sub(r"'[^']{50,}'", "'[DATA_REDACTED]'", error)
        
        # Remove potential numeric IDs
        sanitized = re.sub(r'\b\d{6,}\b', '[ID_REDACTED]', sanitized)
        
        # Limit length
        if len(sanitized) > 500:
            sanitized = sanitized[:500] + "..."
        
        return sanitized
    
    def generate_report(self, results: List[TestResult]) -> TestReport:
        """
        Generate an aggregate report from test results.
        
        Args:
            results: List of TestResult objects
            
        Returns:
            TestReport with aggregate statistics
        """
        # Count by status
        passed = sum(1 for r in results if r.status == TestStatus.PASSED)
        failed = sum(1 for r in results if r.status == TestStatus.FAILED)
        errors = sum(1 for r in results if r.status == TestStatus.ERROR)
        skipped = sum(1 for r in results if r.status == TestStatus.SKIPPED)
        total = len(results)
        
        # Calculate pass rate (excluding skipped)
        tested = total - skipped
        pass_rate = (passed / tested * 100) if tested > 0 else 0.0
        
        # Group errors by type
        errors_by_type = defaultdict(list)
        for r in results:
            if r.sql_error:
                # Extract error type from message
                error_type = "Unknown Error"
                if "syntax" in r.sql_error.lower():
                    error_type = "Syntax Error"
                elif "column" in r.sql_error.lower() or "field" in r.sql_error.lower():
                    error_type = "Column/Field Error"
                elif "table" in r.sql_error.lower():
                    error_type = "Table Error"
                elif "timeout" in r.sql_error.lower():
                    error_type = "Timeout Error"
                elif "connection" in r.sql_error.lower():
                    error_type = "Connection Error"
                
                errors_by_type[error_type].append(r.test_id)
        
        # Group results by tag
        results_by_tag = defaultdict(lambda: {"passed": 0, "failed": 0, "errors": 0, "skipped": 0})
        for r in results:
            for tag in r.tags:
                results_by_tag[tag][r.status.value] += 1
        
        # Execution time statistics
        exec_times = [r.execution_time_ms for r in results if r.execution_time_ms > 0]
        gen_times = [r.generation_time_ms for r in results if r.generation_time_ms > 0]
        
        execution_stats = {}
        if exec_times:
            execution_stats = {
                "total_execution_ms": sum(exec_times),
                "avg_execution_ms": sum(exec_times) / len(exec_times),
                "min_execution_ms": min(exec_times),
                "max_execution_ms": max(exec_times),
                "avg_generation_ms": sum(gen_times) / len(gen_times) if gen_times else 0,
            }
        
        return TestReport(
            timestamp=datetime.utcnow().isoformat(),
            total_tests=total,
            passed=passed,
            failed=failed,
            errors=errors,
            skipped=skipped,
            pass_rate=pass_rate,
            results=results,
            errors_by_type=dict(errors_by_type),
            results_by_tag=dict(results_by_tag),
            execution_stats=execution_stats
        )
    
    def format_report_markdown(self, report: TestReport) -> str:
        """
        Format a report as markdown.
        
        Args:
            report: TestReport to format
            
        Returns:
            Markdown-formatted report string
        """
        lines = [
            "# SQL Test Report",
            "",
            f"**Generated:** {report.timestamp}",
            "",
            "## Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Total Tests | {report.total_tests} |",
            f"| Passed | {report.passed} |",
            f"| Failed | {report.failed} |",
            f"| Errors | {report.errors} |",
            f"| Skipped | {report.skipped} |",
            f"| **Pass Rate** | **{report.pass_rate:.1f}%** |",
            "",
        ]
        
        # Execution statistics
        if report.execution_stats:
            lines.extend([
                "## Execution Statistics",
                "",
                "| Metric | Value |",
                "|--------|-------|",
                f"| Total Time | {report.execution_stats.get('total_execution_ms', 0):.0f} ms |",
                f"| Avg Execution | {report.execution_stats.get('avg_execution_ms', 0):.0f} ms |",
                f"| Min Execution | {report.execution_stats.get('min_execution_ms', 0):.0f} ms |",
                f"| Max Execution | {report.execution_stats.get('max_execution_ms', 0):.0f} ms |",
                f"| Avg SQL Generation | {report.execution_stats.get('avg_generation_ms', 0):.0f} ms |",
                "",
            ])
        
        # Results by tag
        if report.results_by_tag:
            lines.extend([
                "## Results by Tag",
                "",
                "| Tag | Passed | Failed | Errors | Skipped |",
                "|-----|--------|--------|--------|---------|",
            ])
            for tag, counts in sorted(report.results_by_tag.items()):
                lines.append(
                    f"| {tag} | {counts.get('passed', 0)} | {counts.get('failed', 0)} | "
                    f"{counts.get('errors', 0)} | {counts.get('skipped', 0)} |"
                )
            lines.append("")
        
        # Errors by type
        if report.errors_by_type:
            lines.extend([
                "## Errors by Type",
                "",
            ])
            for error_type, test_ids in report.errors_by_type.items():
                lines.append(f"### {error_type} ({len(test_ids)} tests)")
                lines.append("")
                for test_id in test_ids[:10]:  # Limit to 10
                    lines.append(f"- {test_id}")
                if len(test_ids) > 10:
                    lines.append(f"- ... and {len(test_ids) - 10} more")
                lines.append("")
        
        # Failed tests details
        failed_tests = [r for r in report.results if r.status in (TestStatus.FAILED, TestStatus.ERROR)]
        if failed_tests:
            lines.extend([
                "## Failed Tests Details",
                "",
            ])
            for result in failed_tests[:20]:  # Limit to 20
                lines.extend([
                    f"### {result.test_id}",
                    "",
                    f"**Status:** {result.status.value}",
                    f"**Tags:** {', '.join(result.tags) if result.tags else 'none'}",
                    "",
                ])
                if result.sql_error:
                    lines.extend([
                        "**Error:**",
                        "```",
                        result.sql_error[:300],
                        "```",
                        "",
                    ])
                if result.generated_sql:
                    lines.extend([
                        "**Generated SQL:**",
                        "```sql",
                        result.generated_sql[:500],
                        "```",
                        "",
                    ])
                if result.notes:
                    lines.append(f"**Notes:** {result.notes}")
                    lines.append("")
            
            if len(failed_tests) > 20:
                lines.append(f"... and {len(failed_tests) - 20} more failed tests")
                lines.append("")
        
        return "\n".join(lines)


# ============================================
# File Loaders
# ============================================

def load_test_cases_csv(file_path: Path) -> List[TestCase]:
    """
    Load test cases from a CSV file.
    
    Expected columns: test_id, question, expected_sql, tags
    Optional: expected_row_count, expected_result_contains, description, skip, skip_reason
    
    Args:
        file_path: Path to CSV file
        
    Returns:
        List of TestCase objects
    """
    test_cases = []
    
    with open(file_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                test_case = TestCase.from_dict(row)
                test_cases.append(test_case)
            except Exception as e:
                logger.warning(f"Failed to parse row: {e}")
    
    logger.info(f"Loaded {len(test_cases)} test cases from CSV: {file_path}")
    return test_cases


def load_test_cases_json(file_path: Path) -> List[TestCase]:
    """
    Load test cases from a JSON file.
    
    Supports formats:
    - List of test case objects
    - Object with "test_cases", "tests", or "examples" key
    
    Args:
        file_path: Path to JSON file
        
    Returns:
        List of TestCase objects
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Extract test cases from various formats
    if isinstance(data, list):
        raw_cases = data
    elif isinstance(data, dict):
        for key in ['test_cases', 'tests', 'examples', 'queries']:
            if key in data and isinstance(data[key], list):
                raw_cases = data[key]
                break
        else:
            raw_cases = [data]
    else:
        raw_cases = []
    
    test_cases = []
    for i, raw in enumerate(raw_cases):
        try:
            # Ensure test_id exists
            if 'test_id' not in raw and 'id' not in raw:
                raw['test_id'] = f"test_{i:04d}"
            test_case = TestCase.from_dict(raw)
            test_cases.append(test_case)
        except Exception as e:
            logger.warning(f"Failed to parse test case {i}: {e}")
    
    logger.info(f"Loaded {len(test_cases)} test cases from JSON: {file_path}")
    return test_cases


def load_test_cases(file_path: Path) -> List[TestCase]:
    """
    Load test cases from a file (auto-detect format).
    
    Args:
        file_path: Path to test file (CSV or JSON)
        
    Returns:
        List of TestCase objects
    """
    suffix = file_path.suffix.lower()
    
    if suffix == '.csv':
        return load_test_cases_csv(file_path)
    elif suffix == '.json':
        return load_test_cases_json(file_path)
    else:
        # Try JSON first, then CSV
        try:
            return load_test_cases_json(file_path)
        except json.JSONDecodeError:
            return load_test_cases_csv(file_path)


def filter_test_cases(test_cases: List[TestCase], pattern: str) -> List[TestCase]:
    """
    Filter test cases by pattern.
    
    Supports:
    - Glob patterns: "temporal_*", "*_basic"
    - Tag filters: "tag:aggregation"
    - ID filters: "test_001"
    
    Args:
        test_cases: List of test cases
        pattern: Filter pattern
        
    Returns:
        Filtered list of test cases
    """
    import fnmatch
    
    filtered = []
    
    # Check if it's a tag filter
    if pattern.startswith("tag:"):
        tag_filter = pattern[4:].lower()
        for tc in test_cases:
            if any(tag_filter in t.lower() for t in tc.tags):
                filtered.append(tc)
    else:
        # Glob pattern matching on test_id
        for tc in test_cases:
            if fnmatch.fnmatch(tc.test_id.lower(), pattern.lower()):
                filtered.append(tc)
    
    logger.info(f"Filter '{pattern}': {len(filtered)}/{len(test_cases)} tests selected")
    return filtered


# ============================================
# CLI
# ============================================

def print_banner():
    """Print script banner."""
    print("=" * 70)
    print("SQL Test Runner - NL2SQL Accuracy Evaluation")
    print("=" * 70)
    print()


async def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description='Run NL2SQL tests and generate accuracy reports.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python -m app.scripts.run_sql_tests --input tests.csv --output report.md
  python -m app.scripts.run_sql_tests --input tests.json --db-url "duckdb://data/test.db"
  python -m app.scripts.run_sql_tests --filter "temporal_*" --verbose
  python -m app.scripts.run_sql_tests --filter "tag:aggregation"
        """
    )
    
    parser.add_argument(
        '--input', '-i',
        type=Path,
        required=True,
        help='Path to test cases file (CSV or JSON)'
    )
    
    parser.add_argument(
        '--output', '-o',
        type=Path,
        default=None,
        help='Path for output report (default: stdout)'
    )
    
    parser.add_argument(
        '--output-format',
        choices=['markdown', 'json'],
        default='markdown',
        help='Output format (default: markdown)'
    )
    
    parser.add_argument(
        '--db-url',
        type=str,
        default=None,
        help='Database URL (default: from settings or duckdb://data/test.db)'
    )
    
    parser.add_argument(
        '--csv-file',
        type=Path,
        default=None,
        help='CSV file to query directly (creates DuckDB view)'
    )
    
    parser.add_argument(
        '--filter', '-f',
        type=str,
        default=None,
        help='Filter pattern for test selection (e.g., "temporal_*", "tag:aggregation")'
    )
    
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose output'
    )
    
    parser.add_argument(
        '--no-few-shot',
        action='store_true',
        help='Disable few-shot example retrieval'
    )
    
    parser.add_argument(
        '--save-results',
        type=Path,
        default=None,
        help='Save detailed results to JSON file'
    )
    
    args = parser.parse_args()
    
    # Configure logging
    log_level = "DEBUG" if args.verbose else "INFO"
    configure_logging(log_level=log_level, json_logs=False)
    
    print_banner()
    
    try:
        # Validate input file
        if not args.input.exists():
            print(f"ERROR: Input file not found: {args.input}")
            sys.exit(1)
        
        # Load test cases
        print(f"Loading test cases from: {args.input}")
        test_cases = load_test_cases(args.input)
        
        if not test_cases:
            print("ERROR: No test cases found in input file")
            sys.exit(1)
        
        print(f"Loaded {len(test_cases)} test cases")
        
        # Apply filter if specified
        if args.filter:
            test_cases = filter_test_cases(test_cases, args.filter)
            if not test_cases:
                print(f"ERROR: No test cases match filter: {args.filter}")
                sys.exit(1)
        
        # Create SQL service
        print("Initializing SQL service...")
        
        if args.csv_file:
            if not args.csv_file.exists():
                print(f"ERROR: CSV file not found: {args.csv_file}")
                sys.exit(1)
            sql_service = SQLServiceForCSV(
                csv_path=str(args.csv_file),
                enable_few_shot=not args.no_few_shot
            )
        elif args.db_url:
            sql_service = SQLService(
                db_url=args.db_url,
                enable_few_shot=not args.no_few_shot
            )
        else:
            # Try to get from settings or use default
            settings = get_settings()
            db_url = getattr(settings, 'database_url', None) or "duckdb://data/test.db"
            sql_service = SQLService(
                db_url=db_url,
                enable_few_shot=not args.no_few_shot
            )
        
        # Get schema info
        _ = sql_service.get_schema_context()  # Warm up schema cache
        table_count = len(sql_service._discover_tables())
        print(f"Connected to database with {table_count} tables")
        
        # Create and run test runner
        print()
        print(f"Running {len(test_cases)} tests...")
        print("-" * 50)
        
        runner = SQLTestRunner(
            sql_service=sql_service,
            test_cases=test_cases,
            verbose=args.verbose
        )
        
        results = await runner.run_all()
        
        print("-" * 50)
        
        # Generate report
        report = runner.generate_report(results)
        
        # Format and output report
        if args.output_format == 'json':
            report_content = json.dumps(report.to_dict(), indent=2)
        else:
            report_content = runner.format_report_markdown(report)
        
        if args.output:
            with open(args.output, 'w', encoding='utf-8') as f:
                f.write(report_content)
            print(f"\nReport saved to: {args.output}")
        else:
            print()
            print(report_content)
        
        # Save detailed results if requested
        if args.save_results:
            with open(args.save_results, 'w', encoding='utf-8') as f:
                json.dump(report.to_dict(), f, indent=2)
            print(f"Detailed results saved to: {args.save_results}")
        
        # Print summary
        print()
        print("=" * 50)
        print(f"SUMMARY: {report.passed}/{report.total_tests} passed ({report.pass_rate:.1f}%)")
        print("=" * 50)
        
        # Exit with error code if tests failed
        if report.failed > 0 or report.errors > 0:
            sys.exit(1)
        
    except KeyboardInterrupt:
        print("\n\nOperation cancelled by user")
        sys.exit(1)
    except Exception as e:
        logger.exception(f"Test run failed: {e}")
        print(f"\nERROR: {e}")
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
