"""add_config_status_and_step

Revision ID: d4c229c08d0e
Revises: a44745e705ed
Create Date: 2026-04-03 20:13:16.992664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c229c08d0e'
down_revision: Union[str, Sequence[str], None] = 'a44745e705ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with defaults for existing rows
    op.add_column('agent_configs', sa.Column('status', sa.String(), nullable=False, server_default='published'))
    op.add_column('agent_configs', sa.Column('current_step', sa.Integer(), nullable=False, server_default='6'))
    
    # Remove server defaults after migration (optional, keeps schema clean)
    op.alter_column('agent_configs', 'status', server_default=None)
    op.alter_column('agent_configs', 'current_step', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'current_step')
    op.drop_column('agent_configs', 'status')
    # ### end Alembic commands ###
